wandb_version: 1

batch_size:
  desc: null
  value: 32
val_split:
  desc: null
  value: 0.1
epochs:
  desc: null
  value: 1
mode:
  desc: null
  value: fa
activations:
  desc: null
  value:
  - relu
hidden_layers:
  desc: null
  value:
  - 1000
jax_seed:
  desc: null
  value: 0
dataset:
  desc: null
  value: mnist
in_dim:
  desc: null
  value: 1
seq_len:
  desc: null
  value: 1
output_features:
  desc: null
  value: 10
train_set_size:
  desc: null
  value: 50
test_set_size:
  desc: null
  value: 10
lr:
  desc: null
  value: 0.03
momentum:
  desc: null
  value: 0
plot:
  desc: null
  value: true
compute_grad_alignments:
  desc: null
  value: true
wandb_project:
  desc: null
  value: test_project
use_wandb:
  desc: null
  value: true
n:
  desc: null
  value: 5
wandb_entity:
  desc: null
  value: bioflax
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699548523.61886
    t:
      1:
      - 1
      - 12
      - 41
      - 45
      - 55
      2:
      - 1
      - 12
      - 41
      - 45
      - 55
      3:
      - 16
      - 23
      4: 3.11.5
      5: 0.15.12
      8:
      - 5
      13: darwin-x86_64
