
method: grid
program: run_train.py
parameters:
  lr:
    values:
      - 0.001
      - 0.00316
      - 0.01
      - 0.0316
  optimizer:
    values:
      - 'adam'
      - 'sgd'
  epochs:
    value: 50
  wandb_project:
    value: 'weight_init'
  initializer:
    values:
      - 'variance_scaling'
      - 'uniform'
  scale_w:
    values:
      - 0.02
      - 0.1
      - 0.5
      - 1
  scale_b:
    values:
      - 0.02
      - 0.1
      - 0.5
      - 1